allowBuilds:
  '@google/genai': false
  cpu-features: true
  protobufjs: false
  ssh2: true
  tree-sitter-bash: true
minimumReleaseAgeExclude:
  - '@howaboua/pi-codex-conversion@2.2.22'
patchedDependencies:
  '@earendil-works/gondolin': patches/@earendil-works__gondolin.patch
  '@howaboua/pi-codex-conversion@2.2.22': patches/@howaboua__pi-codex-conversion@2.2.22.patch
